version: '3'

services:
  backend:
    build: .
    links:
      - db_xmeme
    ports:
      - '8081:80'
    environment:
      - HOST_IP:"10.5.13.32"
      - HOST_PORT:"8081"

  db_xmeme:
    image: mysql:5.7
    ports:
      - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: xmeme
    volumes:
      - ./backend:/tmp/backend
    command: mysqld --init-file="/tmp/backend/xmeme.sql"
